// <auto-generated />
using Lexus.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lexus.Infra.Migrations
{
    [DbContext(typeof(LexusContext))]
    [Migration("20200801145713_user_table#1")]
    partial class user_table1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Lexus.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasMaxLength(36);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasName("User_Unique");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "1c1afc1e-0f93-4027-b884-cc36828b6223",
                            Password = "secretpass",
                            Username = "nicoolas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
