// <auto-generated />
using Lexus.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lexus.Infra.Migrations
{
    [DbContext(typeof(LexusContext))]
    [Migration("20200801154310_teacher_table#1")]
    partial class teacher_table1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Lexus.Core.Models.Teacher", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasColumnType("VARCHAR(36)");

                    b.Property<string>("EmailAddres")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("TeacherId");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("Lexus.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasMaxLength(36);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasName("User_Unique");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "9a7533b7-4479-4d43-90db-f12993b6a8d3",
                            Password = "secretpass",
                            Username = "nicoolas"
                        });
                });

            modelBuilder.Entity("Lexus.Core.Models.Teacher", b =>
                {
                    b.HasOne("Lexus.Core.Models.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("Lexus.Core.Models.Teacher", "TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
